import { Router } from "express";
import authRoutes from "./authRoutes";
import personsRoutes from "./personsRoutes";
import userRoutes from "./userRoutes";
import vehicleRoutes from "./vehicles/vehicleRoutes";
import vehicleModelRoutes from "./vehicles/vehicleModelRoutes";
import vehicleBrandRoutes from "./vehicles/vehicleBrandRoutes";
import mileageHistoryRoutes from "./vehicles/mileageHistoryRoutes";
import productCategoryRoutes from "./products/productCategoryRoutes"; 
import productRoutes from "./products/productRoutes";
import productTypeRoutes from "./products/productTypeRoutes";
import quotationRoutes from "./work/quotationRoutes";
import taxRoutes from "./work/taxRoutes";
import workOrderRoutes from "./work/workOrderRoutes";
import  WorkProductDetail  from "./work/workProductDetailRoutes";
import  Debtor  from "./work/debtorRoutes";
import Supplier  from "./work/supliersRoutes";
import  StockProduct  from "./products/stock_productsController";
import Companies from "./work/companiesRoutes";
import chatbotRoute from "./chatbotRoutes";
import workOrderTechnicianRoutes from "./work/workOrderTechnician";
import notificationRoutes from "./notificationRoutes";
import gastoRoutes from "./gastoRoutes";
import tipoGastoRoutes from "./tipoGastoRoutes";
import paymentTypeRoutes from "./work/paymentTypeRoutes";
import workPaymentRoutes from "./work/workPaymentRoutes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/persons", personsRoutes);
router.use("/user", userRoutes);
router.use("/vehicles", vehicleRoutes);
router.use("/vehicleModels", vehicleModelRoutes);
router.use("/vehicleBrands", vehicleBrandRoutes);
router.use("/mileageHistories", mileageHistoryRoutes);
router.use("/productCategories", productCategoryRoutes); 
router.use("/products", productRoutes);
router.use("/productTypes", productTypeRoutes);
router.use("/quotations", quotationRoutes);
router.use("/taxes", taxRoutes);
router.use("/workOrders", workOrderRoutes);
router.use("/workProductDetails", WorkProductDetail);
router.use("/debtors", Debtor);
router.use("/suppliers", Supplier);
router.use("/stockProducts", StockProduct);
router.use("/companies", Companies);
router.use("/chatbot", chatbotRoute);
router.use("/workOrderTechnicians", workOrderTechnicianRoutes);
router.use("/notifications", notificationRoutes);
router.use("/gastos", gastoRoutes);
router.use("/tiposGasto", tipoGastoRoutes);
router.use("/paymentTypes", paymentTypeRoutes);
router.use("/workPayments", workPaymentRoutes);

export default router;