// entities/index.ts
export { Person } from "./personsEntity";
export { User } from "./usersEntity";
export { MileageHistory } from "./vehicles/mileageHistoryEntity";
export { PaymentType } from "./work/paymentTypeEntity";
export { Product } from "./products/productEntity";
export { ProductCategory } from "./products/productCategoryEntity";
export { ProductPurchase } from "./products/productPurchaseEntity";
export { ProductType } from "./products/productTypeEntity";
export { Quotation } from "./work/quotationEntity";
export { Tax } from "./work/taxEntity";
export { Vehicle } from "./vehicles/vehicleEntity";
export { VehicleBrand } from "./vehicles/vehicleBrandEntity";
export { VehicleModel } from "./vehicles/vehicleModelEntity";
export { WorkOrder } from "./work/workOrderEntity";
export { WorkPayment } from "./work/workPaymentEntity";
export { WorkProductDetail } from "./work/workProductDetailEntity";
export { WorkTicket } from "./work/workTicketEntity";
export { PurchaseHistory } from "./products/purchaseHistoryEntity";
export { Company } from "./work/companiesEntity";
export { StockProduct } from "./products/stockProductEntity";
export { ProductHistory } from "./products/productsHistoryEntity";
export { Supplier } from "./work/suppliersEntity";
export { Debtor } from "./work/debtorsEntity";
export { WorkOrderTechnician } from "./work/workOrderTechnician";
export {Notification} from "./notificationEntity";